### PR TITLE
Update Bot.js

### PR DESCRIPTION
**Pull request by sasukeuchiha23**

### CODE REVIEW

**Comment by Tarnadas** [comment]
Thx for your pull request. I also think fields will be better and they might bypass the new line limit on mobile Discord. If you have too many line breaks, it will truncate the message on mobile Discord, if it's all in the description.

Could use please check your code with the [JavaScript Standard](https://standardjs.com/) linting rules?
`embed.addField(fieldName,fieldText,true)` will change to `embed.addField(fieldName, fieldText, true)` and `if (fieldText.length > 0) {fieldText += "\n";}` will change to
```js
if (fieldText.length > 0) {
  fieldText += '\n'
}
```

**Comment by sasukeuchiha23** [comment]
To be honest, the code changes aren't mine. I had bookmarked your thread to
create a bot for my shard mates and a guy had formatted the output from
your code. I ran yours successfully but the mobile version of the code was
better using this person's code changes.
https://www.reddit.com/r/SWGalaxyOfHeroes/comments/71904d/i_made_a_discord_bot_for_our_shard_to_track_time/dnje2hf/,
the comment where he had made the changes.

**Review by sasukeuchiha23 — COMMENTED** [review]
Still I'll do the proper linting.

**Comment by sasukeuchiha23** [comment]
[Bot.zip](https://github.com/Tarnadas/shard-payout/files/1337484/Bot.zip)



So i ran JavaScript Standard linting and got this output. Hope this one's good.

**Comment by Tarnadas** [comment]
It's nearly perfect. I will do the rest :D

**Comment by sasukeuchiha23** [comment]
Glad. Thanks. :D

**Pull request merged**
